export const ListProduct = [
    { id : Math.random()* 9999,  name : 'Thiết Bị Điện Tử' , href : '/'},
    { id : Math.random()* 9999,  name : 'Phụ Kiện Điện Tử' , href : '/'},
    { id : Math.random()* 9999,  name : 'TV & Thiết Bị Điện Gia Dụng' , href : '/'},
    { id : Math.random()* 9999,  name : 'Sức Khoẻ & Làm Đẹp' , href : '/'},
    { id : Math.random()* 9999,  name : 'Hàng Mẹ, Bé & Đồ Chơi' , href : '/'},
    { id : Math.random()* 9999,  name : 'Siêu Thị Tạp Hoá' , href : '/'},
    { id : Math.random()* 9999,  name : 'Hàng Gia Dụng & Đời Sống' , href : '/'},
    { id : Math.random()* 9999,  name : 'Thời Trang Nữ' , href : '/'},
    { id : Math.random()* 9999,  name : 'Thời Trang Nam' , href : '/'},
    { id : Math.random()* 9999,  name : 'Phụ Kiện Thời Trang' , href : '/'},
    { id : Math.random()* 9999,  name : 'Thể Thao & Du Lịch' , href : '/'},
    { id : Math.random()* 9999,  name : 'Ôtô, Xe Máy' , href : '/'},
    { id : Math.random()* 9999,  name : 'Thiết Bị Định Vị' , href : '/'},
]